# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorioAncora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creada', models.DateField(auto_now_add=True, null=True)),
                ('fecha_modificada', models.DateField(auto_now=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre')),
                ('procesado', models.BooleanField(default=False, verbose_name='Proceso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PalabraCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creada', models.DateField(auto_now_add=True, null=True)),
                ('fecha_modificada', models.DateField(auto_now=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre')),
                ('cant', models.IntegerField(default=0)),
                ('noun', models.IntegerField(default=0)),
                ('adj', models.IntegerField(default=0)),
                ('det', models.IntegerField(default=0)),
                ('verb', models.IntegerField(default=0)),
                ('conj', models.IntegerField(default=0)),
                ('inter', models.IntegerField(default=0)),
                ('pron', models.IntegerField(default=0)),
                ('adv', models.IntegerField(default=0)),
                ('prep', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PalabraDialecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creada', models.DateField(auto_now_add=True, null=True)),
                ('fecha_modificada', models.DateField(auto_now=True, null=True)),
                ('palabra', models.CharField(blank=True, max_length=300, null=True, verbose_name='Palabra')),
                ('significado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Significado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creada', models.DateField(auto_now_add=True, null=True)),
                ('fecha_modificada', models.DateField(auto_now=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre')),
                ('cant', models.IntegerField(default=0)),
                ('noun', models.IntegerField(default=0)),
                ('adj', models.IntegerField(default=0)),
                ('det', models.IntegerField(default=0)),
                ('verb', models.IntegerField(default=0)),
                ('conj', models.IntegerField(default=0)),
                ('inter', models.IntegerField(default=0)),
                ('pron', models.IntegerField(default=0)),
                ('adv', models.IntegerField(default=0)),
                ('prep', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
