# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# prueba.py
# Created on: 2018-02-03 10:53:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.env.overwriteOutput = True

arcpy.env.overwriteOutput = True
arcpy.env.workspace = r"D:\Python para ArcGIS\GDB\Calidda.gdb"
#input
mallavial = "mallavial"
predios = "predios"
reddomiciliaria = "reddomiciliaria"
#OUTPUT
prediosafectados = "prediosafectados"
areaafectada = "areaafectada"

distancia = "20 Meters"

print "GO"
#!er Analisis
arcpy.Buffer_analysis(
    reddomiciliaria,
    areaafectada,
    distancia,
    "FULL",
    "FLAT",
    "NONE",
    "#"
)

#2do Analisis
arcpy.Clip_analysis(
    predios,
    areaafectada,
    prediosafectados,
    "#"
)


print "FIN"


"""
def add_syle(color, size, dentro):
    return "<CLR {0}='255'><FNT size ='{1}'>{2}</FNT></CLR>".format(
        color, size, dentro)

def FindLabel([id_zona], [muni]):
    return '{0} \n {1}'.format (
        add_syle('red', 10, [muni].upper()),
       add_syle('blue', 8, [id_zona][6:9]))
"""

