# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# prueba.py
# Created on: 2018-02-03 10:53:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Local variables:
shp_origin = r"D:\Python para ArcGIS\SHP\SuperMercado.shp"
campo = "periodocat"

arcpy.AddField_management(
    shp_origin, campo, "DOUBLE"
)

expresion = 'buscar_ubigeo(!UBIGEO!)'
block_code = """
import random
lista = [2014,2015, 2016, 2017]
def buscar_ubigeo(dato):
    return random.choice(lista)
"""

arcpy.CalculateField_management(
    shp_origin,
    campo,
    expresion,
    'PYTHON_9.3',
    block_code
)

print "..... FIELD CREATE"


