# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# prueba.py
# Created on: 2018-02-03 10:53:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

arcpy.env.overwriteOutput = True

# Local variables:
SuperMercado_shp = arcpy.GetParameterAsText(0)
Distance__value_or_field_ = arcpy.GetParameterAsText(1)
Output_Feature_Class = arcpy.GetParameterAsText(2)

# Process: Buffer
arcpy.Buffer_analysis(
    SuperMercado_shp,
    Output_Feature_Class,
    Distance__value_or_field_
)

arcpy.AddMessage("Aera de influencia creada")