# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# geoproceso.py
# Created on: 2018-01-06 11:43:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Ingrese_SHP = ""
Distancia = ""
SHP_con_area_de_influencia = ""

# Process: Buffer
arcpy.Buffer_analysis(Ingrese_SHP, SHP_con_area_de_influencia, Distancia, "FULL", "ROUND", "NONE", "")

