name: ml
channels:
- defaults
- conda-forge
dependencies:
- jupyter_contrib_nbextensions
- h5py
- scipy
- numpy
- pillow
- opencv
- jpeg
- zlib
- freetype
- libtiff
- bleach
- certifi
- cffi
- cycler
- decorator
- entrypoints
- expat
- fire
- html5lib
- icu
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- jedi
- jinja2
- joblib
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- libiconv
- libpng
- libsodium
- libxml2
- markupsafe
- matplotlib
- mistune
- mkl
- nbconvert
- nbformat
- notebook
- numpy
- olefile
- openssl
- pandas
- pandocfilters
- path.py
- patsy
- pcre
- pexpect
- pickleshare
- pip
- prompt_toolkit
- pycparser
- pygments
- pylint
- pyparsing
- pyqt
- python>=3.6.0
- python-dateutil
- pytz
- pyzmq
- qt
- qtconsole
- scipy
- seaborn
- setuptools
- simplegeneric
- sip
- six
- sqlite
- statsmodels
- terminado
- testpath
- tornado
- tqdm
- traitlets
- wcwidth
- wheel
- widgetsnbextension
- xz
- zeromq
- prompt_toolkit
- python-graphviz
- pip:
  - feather-format
  - imutils
  - ipywidgets
  - isoweek
  - pandas_summary
  - pdpbox
  - plotnine
  - rfpimp
  - scikit-optimize
  - sklearn_pandas
  - treeinterpreter
  - tensorflow
  - keras
