# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='SuperCliente',
            fields=[
            ],
            options={
                'verbose_name': 'Super Cliente',
                'verbose_name_plural': 'Super Clientes',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
        ),
    ]
