# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('formacion_inicial_anio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Formación desde anio')),
                ('formacion_ultima_anio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Formación hasta anio')),
                ('institucion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Institucion')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('puesto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Puesto')),
                ('sexo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sexo')),
                ('ruta_cv', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ruta del CV')),
                ('nivel_estudio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nivel de estudio')),
                ('area_estudio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area de estudio')),
                ('algoritmo_nombre_doc', models.CharField(max_length=100, verbose_name='Nombre del archivo')),
                ('algoritmo_texto', models.TextField(verbose_name='Texto')),
                ('algoritmo_numero_paginas', models.IntegerField(blank=True, null=True, verbose_name='Numero de páginas')),
                ('algoritmo_formato_documento', models.CharField(max_length=100, verbose_name='Formato del documento')),
                ('algoritmo_numero_saltos_linea', models.IntegerField(blank=True, null=True, verbose_name='Numero de saltos de linea')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curriculums',
            },
        ),
    ]
