# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Formato del documento')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres')),
                ('fecha_revision', models.DateTimeField(verbose_name='Fecha de revisión')),
                ('nombre_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del archivo')),
                ('puntaje_nombre_documento', models.IntegerField(verbose_name='Puntaje nombre documento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('seccion_laboral', models.TextField(blank=True, null=True, verbose_name='Sección laboral')),
                ('tiene_experiencia', models.BooleanField(default=False, verbose_name='TIene experiencia')),
                ('seccion_estudios', models.TextField(blank=True, null=True, verbose_name='Sección estudios')),
                ('tiene_estudios', models.BooleanField(default=False, verbose_name='Tiene estudios')),
                ('puntaje_orden_estructura', models.IntegerField(blank=True, null=True, verbose_name='Puntaje Orden Estructura')),
                ('frases_innecesarias', models.TextField(blank=True, null=True, verbose_name='Frases innecesarias')),
                ('puntaje_frases_innecesarias', models.IntegerField(blank=True, null=True, verbose_name='Puntaje Frases Innecesarias')),
                ('numero_lineas', models.IntegerField(blank=True, null=True, verbose_name='Numero de lineas')),
                ('numero_paginas', models.IntegerField(blank=True, null=True, verbose_name='Numero de paginas')),
                ('puntaje_longitud', models.IntegerField(blank=True, null=True, verbose_name='Puntaje longitud')),
                ('antiguedad_laboral', models.CharField(blank=True, max_length=100, null=True, verbose_name='Antiguedad laboral')),
                ('puntaje_antiguedad_laboral', models.IntegerField(blank=True, null=True, verbose_name='Puntaje antiguedad laboral')),
                ('fechas_trabajo', models.TextField(blank=True, null=True, verbose_name='Fechas trbajo')),
                ('permanencia_anios', models.TextField(blank=True, null=True, verbose_name='Lista permanencia años')),
                ('puntaje_permanencia_promedio', models.IntegerField(blank=True, null=True, verbose_name='Puntaje permanencia promedio')),
                ('puntaje_orden_cronologico', models.IntegerField(blank=True, null=True, verbose_name='Puntaje orden cronologico')),
                ('verbos_accion', models.TextField(blank=True, null=True, verbose_name='Verbos accion')),
                ('puntaje_verbos_accion', models.IntegerField(blank=True, null=True, verbose_name='Puntaje verbos accion')),
                ('numeros', models.TextField(blank=True, null=True, verbose_name='Numeros')),
                ('puntaje_numeros', models.IntegerField(blank=True, null=True, verbose_name='Puntaje Numeros')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
            ],
            options={
                'verbose_name_plural': 'Data Curriculums',
                'verbose_name': 'Data Curriculum',
            },
        ),
    ]
