# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_datacurriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacurriculum',
            name='tokenized_job_section',
            field=models.TextField(blank=True, null=True, verbose_name='Tokenized job section'),
        ),
    ]
