# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_datacurriculum_tokenized_job_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacurriculum',
            name='new_job_text',
            field=models.TextField(blank=True, null=True, verbose_name='New job text'),
        ),
    ]
