# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nombre')),
                ('cant', models.IntegerField(default=0)),
                ('noun', models.IntegerField(default=0)),
                ('adj', models.IntegerField(default=0)),
                ('det', models.IntegerField(default=0)),
                ('verb', models.IntegerField(default=0)),
                ('conj', models.IntegerField(default=0)),
                ('inter', models.IntegerField(default=0)),
                ('pron', models.IntegerField(default=0)),
                ('adv', models.IntegerField(default=0)),
                ('prep', models.IntegerField(default=0)),
                ('fecha_creada', models.DateField(auto_now_add=True, null=True)),
                ('fecha_modificada', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
